[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

# Setuptools bug causes collision between pypy and cpython artifacts
before-build = "rm -rf {project}/build"